---
name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-python-quality.yaml@main
  docker-build:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-docker-build.yaml@main
    needs: quality
